#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page.
sudo apt-get update
sudo apt-get install nginx -y
sudo chmod -R 755 /var/www
sudo touch /var/www/html/index.html
sudo echo "Holberton School" > index_m.html
sudo mv index_m.html /var/www/html/index.html
sudo service nginx start
redir="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$redir/" /etc/nginx/sites-available/default
sudo service nginx reload
