#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me
# is redirecting to another page.
sudo apt-get update
sudo apt-get install nginx -y
sudo touch /var/www/html/index.html
sudo echo "Holberton School" > index_m.html
sudo mv index_m.html /var/www/html/index.html
sudo service nginx start
redir="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watc\
h?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$redir/" /etc/nginx/sites-available/default
sudo touch /var/www/html/custom_404.html
sudo echo "Ceci n'est pas une page" > custom_404_m.html
sudo mv custom_404_m.html /var/www/html/custom_404.html
e404="server_name _;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\troot \/var\/www\/html;\n\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$e404/" /etc/nginx/sites-available/default
sudo service nginx reload
