#!/usr/bin/env bash
#more lazy

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
sudo service haproxy start
echo "frontend haproxynode
        bind *:80
	mode http
	default_backend backendnodes

backend backendnodes
 	balance roundrobin
	server 972-web-01 34.75.122.42:80 check
	server 972-web-02 35.237.57.197:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
