#!/usr/bin/env bash
#prints numbers from 1-20 and prints which are bad luck in different cultures
i="1"
while [ $i -le 100 ]
do
    if ((i % 3 == 0 && i % 5 == 0))
    then
        echo "FizzBuzz"
    elif ((i % 3 == 0))
    then
        echo "Fizz"
    elif ((i % 5 == 0))
    then
	echo "Buzz"
    else
        echo "$i"
    fi
    ((i++))
done
