#!/usr/bin/env bash
#prints "Holberton School" 10 times, but adds hi in 9th iteration
i="0"
while [ $i -le 9 ]
do 
   if [ "$i" -eq "8" ]
   then
      echo "Holberton School"
      echo "Hi"
      ((i++))
   fi
   echo "Holberton School"
   ((i++))
done
