#!/usr/bin/env bash
#prints "Holberton ..." 10 times, "bad luck" in 4th and "good luck" in 8th
i="1"
while [ $i -le 10 ]
do
   if [ "$i" -eq "4" ]
   then
       echo "bad luck"
       ((i++))
   elif [ "$i" -eq "8" ]
   then
       echo "good luck"
       ((i++))
   else
   echo "Holberton School"
   ((i++))
   fi
done      
