#!/usr/bin/env bash
#prints numbers from 1-20 and prints which are bad luck in different cultures
i="1"
while [ $i -le 20 ]
do
	case $i in 
	     4)
		echo "$i"
		echo "bad luck from China"
		;;
	     9)
		echo "$i"
		echo "bad luck from Japan"
	    	;;
	    17)
		echo "$i"
		echo "bad luck from Italy"
	     	;;
	     *)
		echo "$i"
		;;
	esac
	((i++))
done
	
