#!/usr/bin/env bash
#prints hours and minutes
i="0"
j="1"
while [ $i -le 12 ]
do
      echo "Hora: $i"
      j="1"
      while [ $j -lt 60 ]
      do
      	    echo "$j"
	    ((j++))
      done
      ((i++))
done
