#!/usr/bin/env bash
#request for info about a file
if [ -e "holbertonschool" ]
then
    echo "holbertonschool file exists"
    if [ -s "holbertonschool" ]
    then
	echo "holbetonschool file is empty"
    else
	echo "holbetonschool file is not empty"
fi
    if [ -f "holbetonschool" ]
    then
	echo "holbertonschool file is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
