#!/usr/bin/env bash
# changes nginx user 7 lines
sudo chmod 755 /etc/nginx/nginx.conf
sudo sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo pkill -o apache2
su nginx -c "service nginx restart"
